application:
  name: BitBot
  project: BitBot
  cloud_region: aws/us-east-2
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: the-db
routers:
- name: main
  routes:
  - application_name: BitBot
    paths:
    - /
